USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE CUSTOMER_GOLD AS
SELECT *
FROM STAGING.CUSTOMERS_CLEAN
WHERE CUSTOMER_ID IS NOT NULL;

CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD (
    CUSTOMER_SK NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    CITY STRING,
    STATE STRING,
    REGION STRING,
    ACQUISITION_CHANNEL STRING,
    SIGNUP_DATE DATE,
    EFFECTIVE_FROM TIMESTAMP,
    EFFECTIVE_TO TIMESTAMP,
    IS_CURRENT BOOLEAN
);
INSERT INTO DIM_CUSTOMER_SCD (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CITY,
    STATE,
    REGION,
    ACQUISITION_CHANNEL,
    SIGNUP_DATE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CITY,
    STATE,
    REGION,
    ACQUISITION_CHANNEL,
    SIGNUP_DATE,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
FROM CUSTOMER_GOLD;
-- Expire old records
UPDATE DIM_CUSTOMER_SCD tgt
SET 
    EFFECTIVE_TO = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE
FROM CUSTOMER_GOLD src
WHERE tgt.CUSTOMER_ID = src.CUSTOMER_ID
AND tgt.IS_CURRENT = TRUE
AND (
    NVL(tgt.CITY,'X') <> NVL(src.CITY,'X')
    OR NVL(tgt.STATE,'X') <> NVL(src.STATE,'X')
    OR NVL(tgt.EMAIL,'X') <> NVL(src.EMAIL,'X')
);

-- Insert new version
INSERT INTO DIM_CUSTOMER_SCD (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CITY,
    STATE,
    REGION,
    ACQUISITION_CHANNEL,
    SIGNUP_DATE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT
)
SELECT
    src.CUSTOMER_ID,
    src.FIRST_NAME,
    src.LAST_NAME,
    src.EMAIL,
    src.CITY,
    src.STATE,
    src.REGION,
    src.ACQUISITION_CHANNEL,
    src.SIGNUP_DATE,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
FROM CUSTOMER_GOLD src
JOIN DIM_CUSTOMER_SCD tgt
ON src.CUSTOMER_ID = tgt.CUSTOMER_ID
WHERE tgt.IS_CURRENT = FALSE
AND tgt.EFFECTIVE_TO = (
    SELECT MAX(EFFECTIVE_TO)
    FROM DIM_CUSTOMER_SCD
    WHERE CUSTOMER_ID = src.CUSTOMER_ID
);
SELECT 
    ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY EFFECTIVE_FROM) AS ROW_NUM,
    CUSTOMER_ID,
    CITY,
    IS_CURRENT,
    EFFECTIVE_FROM,
    EFFECTIVE_TO
FROM DIM_CUSTOMER_SCD
WHERE CUSTOMER_ID = 10
ORDER BY EFFECTIVE_FROM;
