USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA ANALYTICS;

-- 1️⃣ Create Stream
CREATE OR REPLACE STREAM CUSTOMER_GOLD_STREAM
ON TABLE CUSTOMER_GOLD;


-- 2️⃣ Create Task (Single Statement Version Using MERGE Pattern)
CREATE OR REPLACE TASK SCD_CUSTOMER_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON * * * * * UTC'
AS

MERGE INTO DIM_CUSTOMER_SCD tgt
USING (
    SELECT *
    FROM CUSTOMER_GOLD_STREAM
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
AND tgt.IS_CURRENT = TRUE

WHEN MATCHED AND (
       NVL(tgt.CITY,'X') <> NVL(src.CITY,'X')
    OR NVL(tgt.STATE,'X') <> NVL(src.STATE,'X')
    OR NVL(tgt.EMAIL,'X') <> NVL(src.EMAIL,'X')
)
THEN UPDATE SET
    EFFECTIVE_TO = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE

WHEN NOT MATCHED
THEN INSERT (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    CITY,
    STATE,
    REGION,
    ACQUISITION_CHANNEL,
    SIGNUP_DATE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT
)
VALUES (
    src.CUSTOMER_ID,
    src.FIRST_NAME,
    src.LAST_NAME,
    src.EMAIL,
    src.CITY,
    src.STATE,
    src.REGION,
    src.ACQUISITION_CHANNEL,
    src.SIGNUP_DATE,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
);

-- 3️⃣ Resume Task
ALTER TASK SCD_CUSTOMER_TASK RESUME;
