USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA ANALYTICS;
SELECT COUNT(*) FROM DIM_CUSTOMER_SCD;
CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID NUMBER AUTOINCREMENT,
    CUSTOMER_SK NUMBER,
    SALE_DATE DATE,
    SALE_AMOUNT NUMBER(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO FACT_SALES (CUSTOMER_SK, SALE_DATE, SALE_AMOUNT)
SELECT
    CUSTOMER_SK,
    CURRENT_DATE(),
    UNIFORM(100,1000,RANDOM())
FROM DIM_CUSTOMER_SCD
WHERE IS_CURRENT = TRUE
LIMIT 100;
SELECT COUNT(*) FROM FACT_SALES;
SELECT 
    f.SALE_ID,
    f.SALE_AMOUNT,
    d.CUSTOMER_ID,
    d.CITY
FROM FACT_SALES f
JOIN DIM_CUSTOMER_SCD d
ON f.CUSTOMER_SK = d.CUSTOMER_SK
LIMIT 10;
CREATE OR REPLACE VIEW VW_SALES_SUMMARY AS
SELECT
    COALESCE(d.CITY, 'Unknown') AS CITY,
    COUNT(f.SALE_ID) AS TOTAL_ORDERS,
    SUM(f.SALE_AMOUNT) AS TOTAL_REVENUE,
    AVG(f.SALE_AMOUNT) AS AVG_ORDER_VALUE
FROM PUBLIC.FACT_SALES f
JOIN ANALYTICS.DIM_CUSTOMER_SCD d
    ON f.CUSTOMER_SK = d.CUSTOMER_SK
WHERE d.IS_CURRENT = TRUE
GROUP BY COALESCE(d.CITY, 'Unknown');
SELECT * FROM VW_SALES_SUMMARY;
CREATE OR REPLACE VIEW VW_DAILY_SALES AS
SELECT
    f.SALE_DATE,
    COUNT(f.SALE_ID) AS TOTAL_ORDERS,
    SUM(f.SALE_AMOUNT) AS TOTAL_REVENUE
FROM PUBLIC.FACT_SALES f
GROUP BY f.SALE_DATE;
SELECT * FROM VW_DAILY_SALES;
SELECT 
    COUNT(*) AS TOTAL_FACT_ROWS,
    COUNT(DISTINCT CUSTOMER_SK) AS DISTINCT_CUSTOMERS
FROM PUBLIC.FACT_SALES;
