USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_SK NUMBER AUTOINCREMENT,
    FULL_DATE DATE,
    DAY NUMBER,
    MONTH NUMBER,
    YEAR NUMBER,
    MONTH_NAME STRING,
    DAY_OF_WEEK STRING,
    QUARTER NUMBER
);
INSERT INTO DIM_DATE (
    FULL_DATE,
    DAY,
    MONTH,
    YEAR,
    MONTH_NAME,
    DAY_OF_WEEK,
    QUARTER
)
SELECT
    DATEADD(DAY, SEQ4(), '2024-01-01') AS FULL_DATE,
    DAY(DATEADD(DAY, SEQ4(), '2024-01-01')),
    MONTH(DATEADD(DAY, SEQ4(), '2024-01-01')),
    YEAR(DATEADD(DAY, SEQ4(), '2024-01-01')),
    TO_CHAR(DATEADD(DAY, SEQ4(), '2024-01-01'), 'MMMM'),
    TO_CHAR(DATEADD(DAY, SEQ4(), '2024-01-01'), 'DY'),
    QUARTER(DATEADD(DAY, SEQ4(), '2024-01-01'))
FROM TABLE(GENERATOR(ROWCOUNT => 1100));
SELECT COUNT(*) FROM DIM_DATE;
ALTER TABLE PUBLIC.FACT_SALES
ADD COLUMN DATE_SK NUMBER;
UPDATE PUBLIC.FACT_SALES f
SET DATE_SK = d.DATE_SK
FROM ANALYTICS.DIM_DATE d
WHERE f.SALE_DATE = d.FULL_DATE;
SELECT COUNT(*) 
FROM PUBLIC.FACT_SALES
WHERE DATE_SK IS NULL;

