USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA ANALYTICS;
CREATE OR REPLACE VIEW VW_YEARLY_REVENUE AS
SELECT
    d.YEAR,
    SUM(f.SALE_AMOUNT) AS TOTAL_REVENUE
FROM PUBLIC.FACT_SALES f
JOIN ANALYTICS.DIM_DATE d
ON f.DATE_SK = d.DATE_SK
GROUP BY d.YEAR
ORDER BY d.YEAR;
DESC TABLE ANALYTICS.DIM_DATE;
CREATE OR REPLACE VIEW VW_TIME_REVENUE_SUMMARY AS
SELECT
    d.YEAR,
    d.MONTH,
    d.MONTH_NAME,
    SUM(f.SALE_AMOUNT) AS TOTAL_REVENUE,
    COUNT(f.SALE_ID) AS TOTAL_ORDERS
FROM PUBLIC.FACT_SALES f
JOIN ANALYTICS.DIM_DATE d
    ON f.DATE_SK = d.DATE_SK
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME
ORDER BY d.YEAR, d.MONTH;
SELECT * FROM VW_TIME_REVENUE_SUMMARY;
USE DATABASE RETAIL_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW ANALYTICS.VW_REVENUE_BY_REGION AS
SELECT
    c.REGION,
    SUM(f.SALE_AMOUNT) AS TOTAL_REVENUE,
    COUNT(f.SALE_ID) AS TOTAL_ORDERS
FROM RETAIL_ANALYTICS.PUBLIC.FACT_SALES f
JOIN RETAIL_ANALYTICS.ANALYTICS.DIM_CUSTOMER_SCD c
    ON f.CUSTOMER_SK = c.CUSTOMER_SK
WHERE c.IS_CURRENT = TRUE
GROUP BY c.REGION;
SELECT * FROM ANALYTICS.VW_REVENUE_BY_REGION;
CREATE OR REPLACE VIEW ANALYTICS.VW_EXECUTIVE_DASHBOARD AS
SELECT
    COUNT(DISTINCT f.SALE_ID) AS TOTAL_ORDERS,
    SUM(f.SALE_AMOUNT) AS TOTAL_REVENUE,
    AVG(f.SALE_AMOUNT) AS AVG_ORDER_VALUE,
    COUNT(DISTINCT f.CUSTOMER_SK) AS TOTAL_CUSTOMERS
FROM RETAIL_ANALYTICS.PUBLIC.FACT_SALES f;
SELECT * FROM ANALYTICS.VW_EXECUTIVE_DASHBOARD;
CREATE OR REPLACE VIEW ANALYTICS.VW_FULL_DASHBOARD AS
SELECT
    d.YEAR,
    d.MONTH,
    c.REGION,
    COUNT(f.SALE_ID) AS TOTAL_ORDERS,
    SUM(f.SALE_AMOUNT) AS TOTAL_REVENUE,
    AVG(f.SALE_AMOUNT) AS AVG_ORDER_VALUE
FROM RETAIL_ANALYTICS.PUBLIC.FACT_SALES f
JOIN RETAIL_ANALYTICS.ANALYTICS.DIM_DATE d
    ON f.DATE_SK = d.DATE_SK
JOIN RETAIL_ANALYTICS.ANALYTICS.DIM_CUSTOMER_SCD c
    ON f.CUSTOMER_SK = c.CUSTOMER_SK
WHERE c.IS_CURRENT = TRUE
GROUP BY d.YEAR, d.MONTH, c.REGION
ORDER BY d.YEAR, d.MONTH;
SELECT * FROM ANALYTICS.VW_FULL_DASHBOARD;

